export const footerContent = [
    { key: "footer_description", value: "Your one-stop shop for premium gadgets and accessories.", group: "footer" },
    { key: "contact_email", value: "support@konnecttech.com", group: "contact" },
    { key: "contact_phone", value: "+254 712 345 678", group: "contact" },
    { key: "contact_address", value: "Tech Plaza, Nairobi, Kenya", group: "contact" },
    { key: "social_facebook", value: "https://facebook.com", group: "social" },
    { key: "social_twitter", value: "https://twitter.com", group: "social" },
    { key: "social_instagram", value: "https://instagram.com", group: "social" },
    { key: "social_linkedin", value: "https://linkedin.com", group: "social" },
];

export const products = [
    {
        id: 1,
        name: 'Classic Leather Backpack',
        description: 'A stylish and durable backpack for everyday use.',
        price: 59.99,
        category: 'Backpacks',
        image: '/backpack.jpg',
        subcategory: 'Leather',
        rating: 4.5,
        reviews: 120,
    },
    {
        id: 2,
        name: 'Wireless Bluetooth Speaker',
        description: 'Portable speaker with high-quality sound.',
        price: 89.99,
        category: 'Speakers',
        image: '/bluetooth_speakers.jpg',
        subcategory: 'Portable',
        rating: 4.8,
        reviews: 250,
    },
    {
        id: 3,
        name: 'Professional DSLR Camera',
        description: 'Capture stunning photos with this professional-grade camera.',
        price: 899.99,
        category: 'Cameras',
        image: '/camera.jpg',
        subcategory: 'DSLR',
        rating: 4.9,
        reviews: 300,
    },
    {
        id: 4,
        name: 'Ergonomic Wireless Mouse',
        description: 'Comfortable and precise mouse for all-day use.',
        price: 29.99,
        category: 'Computer Accessories',
        image: '/computer_accessories.jpg',
        subcategory: 'Mice',
        rating: 4.6,
        reviews: 150,
    },
    {
        id: 5,
        name: 'Ultra-Thin Laptop',
        description: 'Lightweight and powerful laptop for professionals.',
        price: 1299.99,
        category: 'Computers',
        image: '/computers.jpg',
        subcategory: 'Laptops',
        rating: 4.7,
        reviews: 180,
    },
    {
        id: 6,
        name: 'High-Performance Drone',
        description: 'Capture breathtaking aerial footage with this advanced drone.',
        price: 799.99,
        category: 'Drones',
        image: '/drone.jpg',
        subcategory: 'Quadcopters',
        rating: 4.8,
        reviews: 220,
    },
    {
        id: 7,
        name: 'Noise-Cancelling Earphones',
        description: 'Immerse yourself in music with these noise-cancelling earphones.',
        price: 149.99,
        category: 'Earphones',
        image: '/earphones.jpg',
        subcategory: 'In-Ear',
        rating: 4.7,
        reviews: 200,
    },
    {
        id: 8,
        name: 'Modern Accent Chair',
        description: 'A stylish and comfortable chair for any room.',
        price: 249.99,
        category: 'Furniture',
        image: '/furniture.jpg',
        subcategory: 'Chairs',
        rating: 4.6,
        reviews: 130,
    },
    {
        id: 9,
        name: 'Mechanical Gaming Keyboard',
        description: 'Responsive and durable keyboard for the ultimate gaming experience.',
        price: 129.99,
        category: 'Gaming Gear',
        image: '/gaming_gear.jpg',
        subcategory: 'Keyboards',
        rating: 4.8,
        reviews: 280,
    },
    {
        id: 10,
        name: 'Curved Ultrawide Monitor',
        description: 'Immersive and productive monitor for work and play.',
        price: 599.99,
        category: 'Monitors',
        image: '/monitors.jpg',
        subcategory: 'Ultrawide',
        rating: 4.7,
        reviews: 190,
    },
    {
        id: 11,
        name: 'Fast-Charging Power Bank',
        description: 'Keep your devices charged on the go with this power bank.',
        price: 39.99,
        category: 'Phone Accessories',
        image: '/phone_accessories.jpg',
        subcategory: 'Power Banks',
        rating: 4.6,
        reviews: 160,
    },
    {
        id: 12,
        name: 'Fitness Tracker Smartwatch',
        description: 'Track your fitness and stay connected with this smartwatch.',
        price: 199.99,
        category: 'Wearables',
        image: '/wearable.jpg',
        subcategory: 'Smartwatches',
        rating: 4.7,
        reviews: 210,
    }
];
